title: Derek Jones
description: M.S. Biology | Data Science and Markets Hobbyist

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: null
``` :contentReference[oaicite:10]{index=10}.
